### ISSUE TITLE
[feat]: Home tab

### ISSUE THREAD

**Issue by BitcoinMechanic** [Start9Labs/embassy-os#1825] opened 2022-09-24 06:20 UTC
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature.

### Describe the Feature Request

This would be in addition to "Services, Embassy, Marketplace, Notifications" along the left panel.

It would be customizable. It could contain a few user-chosen stats from "Embassy -> Monitor" i.e the temperature of the pi/pro, RAM usage, space left on drive, any external drives connected etc.

If could say how many services you have running. How many you have installed. How many are inactive.

A service could feature - or be "bookmarked" and you could always have its health checks on display or a config option from the service that users might like to toggle on and off. For example you might have CLN up there with the CLBOSS config option on display, just so you know it's currently running and have the easy ability to turn it off/back on if you like.

Notifications could scroll on the right hand side.

You could have a "days since last backup" counter.

And prompts about service/EOS updates, along with new services getting added to marketplaces.

Even widgets, cool stuff like saying "Service X has an uptime of 99.131%!" 

Tor network health monitor even!

### Describe the Use Case

For when people want a customizable home page that would be a logical place to just leave a dedicated Embassy tab for in their browser. Currently that's possibly Services, but a home tab would feel more natural and welcoming.  It allows users to design their own experience.

### Describe Preferred Solution

It can be just added by designing and embellishing this as we go, without touching anything else - except maybe services upon installation could ask "Would you like to add this service to your home tab?"

### Anything else?

This could complicate things upon completing initial setup though I think an empty home tab wouldn't be too odd. And it would contain some basic suggested info anyway - like days since last backup: zero!

We wouldn't want to annoy users with a bunch more questions/options after initial setup but there wouldn't really be anything to add until they start installing services anyway except for basic stats about their Embassy. 

The flow for setting up a new phone or laptop is far more annoying than we'd need to be because it can be empty and users can totally ignore it if they wish.

**Comment by kn0wmad** [comment] 2022-09-25 18:18
Probably a duplicate of #1647

**Comment by MattDHill** [comment] 2022-09-25 18:29
Yes

**Comment by MattDHill** [comment] 2022-09-26 22:00
Closing as duplicate, will still be visible from the other issue

**Closed by MattDHill** 2022-09-26 22:00 UTC
Labels: Enhancement
