### ISSUE TITLE
[bug]: Bitcoind says "starting" (no option to stop service) while syncing. 

### ISSUE THREAD

**Issue by BitcoinMechanic** [Start9Labs/embassy-os#915] opened 2021-12-06 18:12 UTC
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem, without success.

### EmbassyOS Version

0.3.0

### Device

Laptop/Desktop

### Device OS

MacOS

### Device OS Version

10.14.6

### Browser

Firefox

### Browser Version

94.0.2

### Current Behavior

![Screen Shot 2021-12-06 at 10 05 56 AM](https://user-images.githubusercontent.com/45926711/144899262-a1f4de7e-f2a1-43bf-8f24-772b6e5d6089.png)

### Expected Behavior

Should say "running" I believe.

### Steps to Reproduce

Install and start Bitcoind with default config.

### Anything else?

The logs show that it is continuing to sync as expected.

**Comment by BitcoinMechanic** [comment] 2021-12-06 18:41
embassy-cli db dump | grep -C5 starting
            "to": {}
          },
          "actions": {
            "reindex": {
              "name": "Reindex Blockchain",
              "description": "Rebuilds the block and chainstate databases starting from genesis. If blocks already exist on disk, these are used rather than being redownloaded. However, since embassy bitcoin nodes are pruned by default, this usually means downloading the entire blockchain over again.",
              "warning": "Blocks not stored on disk will be redownloaded in order to rebuild the database. If your node is pruned (embasssy nodes are pruned by default), this action is equivalent to syncing the node from scratch, so this process could take a couple of weeks.",
              "implementation": {
                "type": "docker",
                "image": "main",
                "system": false,
--
        },
        "installed": {
          "status": {
            "configured": true,
            "main": {
              "status": "starting"
            },
            "dependency-errors": {}
          },
          "manifest": {
            "eos-version": "0.3.0",
--
              "to": {}
            },
            "actions": {
              "reindex": {
                "name": "Reindex Blockchain",
                "description": "Rebuilds the block and chainstate databases starting from genesis. If blocks already exist on disk, these are used rather than being redownloaded. However, since embassy bitcoin nodes are pruned by default, this usually means downloading the entire blockchain over again.",
                "warning": "Blocks not stored on disk will be redownloaded in order to rebuild the database. If your node is pruned (embasssy nodes are pruned by default), this action is equivalent to syncing the node from scratch, so this process could take a couple of weeks.",
                "implementation": {
                  "type": "docker",
                  "image": "main",
                  "system": false,

**Comment by BitcoinMechanic** [comment] 2021-12-06 18:47
Might be a dup of #906

**Comment by ProofOfKeags** [comment] 2021-12-06 22:34
This is not a duplicate of #906. If you wish to be able to "cancel" a stop request then you are correct and that functionality at present does not exist. I am not opposed to adding it but I am hesitant to put it in scope for 0.3.0. Things work fine as is and there may be a handful of edge cases we have to solve in order to make this possible.

**Comment by chrisguida** [comment] 2021-12-07 23:09
@ProofOfKeags I think you misunderstood the bug. The UI says "Starting..." while the service is in fact running.

**Comment by ProofOfKeags** [comment] 2021-12-09 18:25
Should I understand this to mean that it says "Starting..." indefinitely?

**Comment by BitcoinMechanic** [comment] 2021-12-09 19:10
I didn't complete IBD on that build. This bug might be hard to repro....

**Comment by ProofOfKeags** [comment] 2021-12-09 19:25
What does IBD have anything to with this? I haven't experienced this recently and I have a node that I was able to stop that was still doing IBD. Are you sure this is an IBD issue?

**Comment by BitcoinMechanic** [comment] 2021-12-09 20:04
No I'm not. I was thinking it may have stopped once IBD completed that's all, but wasn't able to confirm because it was blocking too many other things for me to test.

**Closed** 2022-03-10 20:03 UTC
Labels: Bug, Invalid, UI, embassyd, Needs Scoping, P2 - Desirable
