### ISSUE TITLE
UI Bug - Need to show completion screen after initialization

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/embassy-os#761] opened 2021-11-02 01:56 UTC
Initialization screen does not display address info after file download, instead remains on 100% initialization screen

Reported by: @kn0wmad

**Comment by MattDHill** [comment] 2021-11-02 04:45
Was unable to reproduce this, but made some changes to related code, so maybe it's fixed now. Please check and document repro steps if you are able to reproduce.

**Closed** 2021-11-09 22:44 UTC
Labels: Bug, UI, P1 - Blocks Release
