### ISSUE TITLE
Disk not recognized

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/embassy-os#1097] opened 2022-01-19 16:52 UTC
...as a valid LUKS device, again

![image](https://user-images.githubusercontent.com/39687477/150177015-8e2ec481-5f9f-458c-9bfd-88acf40a609b.png)

**Comment by dr-bonez** [comment] 2022-01-19 18:42
duplicate of #1019

**Closed by dr-bonez** 2022-01-19 18:42 UTC
Labels: Bug, embassyd, P0 - Blocks Dev
