### ISSUE TITLE
Auto-config generating an error instead of auto-configuring

### ISSUE THREAD

**Issue by chrisguida** [Start9Labs/embassy-os#797] opened 2021-11-14 15:57 UTC
![Screenshot from 2021-11-14 09-55-35](https://user-images.githubusercontent.com/7445670/141688438-94d35fcd-3617-4799-a395-c4bba57fec40.png)

**Comment by ProofOfKeags** [comment] 2021-11-15 17:25
In general this cannot be solved by the OS as the autoconfigure rules are defined by the package iirc. However any failure to autoconfigure should probably fall back to something that takes manual intervention. If this is not possible, in general, then this would have to be solved in the sdk by machine checking the autoconfigure logic against the config provided by the dependent package.

**Comment by elvece** [comment] 2021-11-15 21:49
@chrisguida Can you provide some more context for this error and reference the config rules being used?

Is the situation that a predicate is set in the config spec but there is no accompanying rule?

Regardless, there should be a better UX around this situation, but I first want to understand how it arose.

**Comment by chrisguida** [comment] 2021-11-15 22:06
Yes, I was updating bwt with a new rpc call. The original rpc calls all autoconfigured fine, but I needed to add a new one. So I changed the manifest to add a new rpc call and re-uploaded, and the UI correctly indicated that I'd need to auto-config for the new rpc call. But when I clicked auto-config, it gave me this error. I'm guessing that means that this will probably pop up in prod (at least) whenever we add a new rpc call to an updated app.

**Comment by ProofOfKeags** [comment] 2021-11-19 23:28
OK after conversing with Aiden here is what I understand about this ticket.

Fundamentally from the OS's perspective there are two things that are supported in the autoconfigure API

`check :: Config -> Result<(), Error>`
`autoconfig :: Config -> Result<Config, Error>`

Due to Turing Completeness we can never guarantee the success of either of these functions. Therefore we *must* handle the error case always. So at a bare minimum the front end needs to prepare for a case where the error comes in.

However, the issue that is presented above here is an issue where the compat image is wrongfully returning an error if the suggestion does not satisfy the rule. Instead the desired behavior should be for it to return the best possible config, even if it doesn't satisfy all of the rules.

According to @dr-bonez the Frontend should already be able to handle the fallback to manual configuration since the config returned after autoconfig will be rendered by the front end without issue.

As such there are two issues here. The one here is with the compat image itself throwing errors when it probably shouldn't.

**Comment by elvece** [comment] 2021-11-20 00:17
Ok, how the rule parser works to my current understanding is that it attempts to apply the suggestion, and then checks the config again to make sure the rules are met. If they were not met after the suggestions were applied, it errors with the failed rule(s), and the compat image propagates this up to the FE. 

This comment suggests that in the autoconfig case, we should _never_ error, and always return the updated config (which will have the best possible configuration). In that case, do we also need to return a list of the suggestions that failed? Or do we error with a list of the suggestions *and* the best possible config? If not, how does the FE know which items need manual configuration @dr-bonez ? 

Is the FE expecting a success or an error in this situation?

In either case, I need clarity on what the expected return type should be so that the FE can appropriately handle the fallback to manual configuration.

**Comment by dr-bonez** [comment] 2021-11-20 05:26
Hmm this is an interesting idea. I could allow autoconfigure to fail, and expect it to still return the modified config. So an error _and_ a response.

**Comment by chrisguida** [comment] 2021-11-21 17:50
There is no reason the suggestion should have failed in this case, it was just adding a new rpc call, several of which already existed.

**Comment by elvece** [comment] 2021-11-21 18:02
@chrisguida I'm confused how the failure happened. Did you add a configuration to the config spec, but not add a rule/suggestion in the config rules? Can you add a reference to the commit showing the code changes that produced this error to this thread?

**Comment by chrisguida** [comment] 2021-11-21 20:37
Upon closer inspection, there was an issue with the rule I'd added, so, my bad.

```
- rule: '''users.[first(item => ''item.name = "bwt")].allowed-calls.* = "createwallet"'
  description: 'RPC user "bwt" must have "createwallet" enabled'
  suggestions:
    - PUSH:
        to: 'users.[first(item => ''item.name = "bwt")].allowed-calls'
        value: "estimatesmartfee"
```

The last line was an rpc call that had already been added. I suppose this made the suggestion fail.

The error message threw me off, do you think there would be any way to improve the messaging when the suggestion fails?

**Comment by ProofOfKeags** [comment] 2021-11-22 17:13
Despite the fact that this error originated within a misconfigured service, the fact that the config rules language is not decidable means we still have to handle the case where an error is produced by the autoconfigure process. The issue isn't with the error message perse, but with the entire error generation and propagation process.

**Comment by elvece** [comment] 2021-11-22 17:18
> Hmm this is an interesting idea. I could allow autoconfigure to fail, and expect it to still return the modified config. So an error _and_ a response.

@dr-bonez lmk if this is the best approach and I can get it implemented.

**Comment by dr-bonez** [comment] 2021-11-23 21:49
We'll put off that feature into the next release since it can be made backwards compatible. For now lets leave compat alone. This can be fixed in bwt.

**Comment by dr-bonez** [comment] 2021-11-23 21:50
@chrisguida to summarize, this is happening because the suggestions you set for your autoconfigure rule fail to satisfy the predicate. If you fix your suggestion it should be fine.

**Comment by ProofOfKeags** [comment] 2021-11-23 21:50
Deescalating to P2.

**Comment by ProofOfKeags** [comment] 2021-11-23 21:52
This ticket is tracking the general problem of autoconfiguration error handling, not the specific problem with BWT.

**Comment by elvece** [comment] 2021-12-06 16:54
Per discussion, Aiden and I are in favor of closing this ticket in favor of implementing the suggested solution into the new feature set for auto-config, which will come out in the 0.3.x series. Compat will ultimately be deprecated in favor of a different set of system tooling / custom developer configurations, and it would be valuable to design this new tooling set with this feature in mind.

**Comment by chrisguida** [comment] 2021-12-07 23:32
Seems like we can just keep it open and move it to the 031 board?

**Closed** 2022-03-10 20:02 UTC
Labels: Bug, Won't Fix, UI, P2 - Desirable, System Images
