### ISSUE TITLE
[bug]: Notifications tab takes increasingly long time to load. Deleting notifications doesn't make a difference.

### ISSUE THREAD

**Issue by BitcoinMechanic** [Start9Labs/embassy-os#1489] opened 2022-06-06 16:48 UTC
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem, without success.

### EmbassyOS Version

0.3.0~3

### Device

Laptop/Desktop

### Device OS

MacOS

### Device OS Version

10.14.6

### Browser

Firefox

### Browser Version

99.0.1

### Current Behavior

2 minutes + to load notifications.

### Expected Behavior

Should be a few seconds.

### Steps to Reproduce

Load notifications on a box that has been running for some months that has stacked up a lot of notifications. Shouldn't matter if they've been deleted or not.

**Comment by MattDHill** [comment] 2022-07-25 18:55
Unable to reproduce with 0311, but leaving open to confirm with public usage

**Comment by BitcoinMechanic** [comment] 2022-07-26 03:11
@chrisguida Has the issue too I believe

**Comment by MattDHill** [comment] 2022-07-26 16:25
If you currently have this issue, please watch the BE logs at the time of request. If we have enough logging in place, it may reveal where this is getting hung up. @dr-bonez anything else you'd like to see?

**Comment by BitcoinMechanic** [comment] 2022-07-26 16:58
I don't currently have the issue.

**Comment by dr-bonez** [comment] 2022-09-08 16:56
should be fixed by #1763

**Closed by dr-bonez** 2022-09-08 16:56 UTC
Labels: Bug, P2 - Desirable, Needs Diagnosis, Performance
