### ISSUE TITLE
Cannot reach Embassy from the setup app when using iOS 15.1 / 15.0.2 / CalyxOS 2.11.0

### ISSUE THREAD

**Issue by cryptodread** [Start9Labs/embassy-os#836] opened 2021-11-23 00:44 UTC
Please fill out as much detail as possible:

When trying to use the start up on my embassy, error message on the phone was "cannot reach server" (pic attached).
Phones attempted on the same network (2.4Ghz and 5GHz):
- iPhone 7, iOS15.1
- iPhone 12ProMax , iOS15.0.2
- Pixel 5a, CalyxOS 2.11.0
- Pixel 3, Android 12

The Pixel 3 is the only phone that worked

**To Reproduce**
1. Go to setup app
2. Type in the product key
3.  See error

**Comment by cryptodread** [comment] 2021-11-23 00:45
![Screenshot_20211122-183705](https://user-images.githubusercontent.com/34528298/142955872-81567bd8-d6e6-45f5-abf7-d792df8160e4.png)

**Comment by cryptodread** [comment] 2021-11-23 00:46
![20211122_182803_3229186150562953555](https://user-images.githubusercontent.com/34528298/142955949-1b1b464b-4c19-4a27-a782-990025eeb3ea.jpg)

**Comment by MattDHill** [comment] 2021-11-26 16:03
Closing, was caused by networking issues.

**Closed by MattDHill** 2021-11-26 16:03 UTC
Labels: Bug, Needs Triage
