### ISSUE TITLE
[bug]: Health checks sometimes try to run when there's another with the same name already running

### ISSUE THREAD

**Issue by chrisguida** [Start9Labs/embassy-os#899] opened 2021-12-04 03:34 UTC
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem, without success.

### EmbassyOS Version

030

### Device

Laptop/Desktop

### Device OS

MacOS

### Device OS Version

it doesn't matter

### Browser

Other

### Browser Version

also doesn't matter

### Current Behavior

Embassyd sometimes runs health checks on top of health checks with the same name, resulting in an error message. This seems to especially affect users running embassy-os on an HDD.

### Expected Behavior

Embassyd should not attempt to start a (health check) docker container with the same name as a container that is already running.

### Steps to Reproduce

1. Set up embassy-os on an HDD
2. Start syncing bitcoin
3. See the below error (screenshot)

I occasionally see this error when syncing bitcoin on my SSD. I almost always see it when syncing bitcoin on my HDD.

### Anything else?

<img width="1165" alt="Screen Shot 2021-12-03 at 9 27 26 PM" src="https://user-images.githubusercontent.com/7445670/144695396-c8c4e75e-f417-46a4-a5b4-3bca48457aab.png">

**Comment by ProofOfKeags** [comment] 2021-12-04 20:25
@dr-bonez is this a duplicate of #867 ?

**Comment by dr-bonez** [comment] 2021-12-08 15:30
It's not a duplicate but could be related. Unsure yet.

**Closed** 2022-01-13 02:48 UTC
Labels: Bug, embassyd, P1 - Blocks Release
