### ISSUE TITLE
Installs/Updates sometimes hang indefinitely

### ISSUE THREAD

**Issue by ProofOfKeags** [Start9Labs/embassy-os#513] opened 2021-09-23 19:30 UTC
uninstalls of bitcoind hang forever, and updates ("embassy-cli package install bitcoind") get stuck at 99 or 100% at least several minutes, sometimes forever. Only way to remedy is to run nukem and start over

Reported by @chrisguida

**Comment by DrewAns** [comment] 2021-11-17 00:14
Install of btc hanging on 100%

**Comment by dr-bonez** [comment] 2021-11-19 02:42
@DrewAns next time this happens, drop everything and call me over. I cannot reproduce.

**Comment by DrewAns** [comment] 2021-11-19 02:59
Will do

**Comment by ProofOfKeags** [comment] 2021-11-19 21:34
Is this still blocking anything?

**Comment by dr-bonez** [comment] 2021-11-23 21:55
Unless someone can repro this reliably, I'm inclined to close this. Now that #816 was merged, a restart will fix this.

**Comment by chrisguida** [comment] 2021-11-24 00:14
This happens fairly often if I forget to stop the service before updating. It happened to me 2-3 times today.

**Comment by dr-bonez** [comment] 2021-11-24 00:16
Are you in the latest commit hash? Or at least after the commit about transient states?

**Comment by chrisguida** [comment] 2021-11-24 15:50
No, will update and report back. My understanding is that #816 doesn't fix the bug, it only allows you to recover via reboot

**Comment by ProofOfKeags** [comment] 2021-11-24 17:01
It does both a recovery, as well as preventing at least one of the causes in the first place.

**Comment by chrisguida** [comment] 2021-11-25 02:18
Confirmed this bug still exists when operating on a service that is still running

**Comment by dr-bonez** [comment] 2021-11-27 00:02
Please collect more information about the conditions that cause this. I have yet to reproduce.

**Comment by chrisguida** [comment] 2021-11-27 01:09
I have tried this in a few cases where it was happening consistently before and it no longer appears to be happening. Closing.

**Closed by chrisguida** 2021-11-27 01:09 UTC
Labels: Bug, embassyd, P1 - Blocks Release, Undiagnosed
