### ISSUE TITLE
Paginate logs

### ISSUE THREAD

**Issue by DrewAns** [Start9Labs/embassy-os#400] opened 2021-08-09 22:07 UTC

**Comment by chrisguida** [comment] 2021-09-10 00:41
This looks done? @DrewAns

**Comment by chrisguida** [comment] 2021-09-10 00:50
Also this looks to be a duplicate of https://github.com/Start9Labs/embassy-os/issues/4

**Comment by ProofOfKeags** [comment] 2021-09-22 16:51
Closing as duplicate

**Closed by ProofOfKeags** 2021-09-22 16:51 UTC
Labels: UI
