### ISSUE TITLE
BUG: package uninstall failure bricks system

### ISSUE THREAD

**Issue by chrisguida** [Start9Labs/embassy-os#787] opened 2021-11-11 13:44 UTC

**Comment by chrisguida** [comment] 2021-11-11 13:44
<img width="522" alt="Screen Shot 2021-11-11 at 7 43 18 AM" src="https://user-images.githubusercontent.com/7445670/141308485-31cddcea-7dec-4b1b-a5dd-f9fb4172c32a.png">

**Comment by dr-bonez** [comment] 2021-11-15 19:30
duplicate of #754

**Closed by dr-bonez** 2021-11-15 19:30 UTC
Labels: Bug, embassyd, P1 - Blocks Release
