### ISSUE TITLE
PhotoView not getting latest state from File Browser

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/embassy-os#881] opened 2021-12-01 15:51 UTC
When PV is running, and FB is uninstalled out from under it, and then re-installed and started, PV does not see that FB is running.  

![image](https://user-images.githubusercontent.com/39687477/144267131-09c6be54-13ba-4cf3-bd84-b33388386474.png)

A re-install of PV fixes as a workaround.

Reported by @kn0wmad

**Comment by ProofOfKeags** [comment] 2021-12-01 18:10
this is originally reported in #868 the problem is pervasive, closing as duplicate.

**Closed by ProofOfKeags** 2021-12-01 18:10 UTC
Labels: Bug, Needs Scoping, P2 - Desirable
