### ISSUE TITLE
[feat]: limit overall resource usage of docker containers

### ISSUE THREAD

**Issue by dr-bonez** [Start9Labs/embassy-os#1151] opened 2022-01-28 21:15 UTC
afaict this can be done with cgroups.

I suspect most of our systemic woes are due to the system reaching max memory or cpu usage. This is likely causing certain important system tools to starve.

**Comment by ProofOfKeags** [comment] 2022-01-31 17:01
duplicate of #1138

**Closed by ProofOfKeags** 2022-01-31 17:01 UTC
Labels: Enhancement, embassyd, P1 - Blocks Release
