### ISSUE TITLE
FE BUG: package status shows "needs config" even when service is already configured

### ISSUE THREAD

**Issue by chrisguida** [Start9Labs/embassy-os#673] opened 2021-10-13 23:31 UTC

**Comment by MattDHill** [comment] 2021-10-14 04:09
After investigating a couple of Lucy's bug reports, I believe this may be an issue resulting from an underlying type mismatch between BE and FE, causing the UI to explode and not react to further updates from patch-db. #674

**Comment by chrisguida** [comment] 2021-10-14 04:32
> Please verify `configured: true` on the package data entry. I strongly suspect this is a BE issue.

Yes, that's how I knew the service was configured.

**Comment by ProofOfKeags** [comment] 2021-10-14 21:38
I have not been able to reproduce this since #674 was closed. Closing

**Closed by ProofOfKeags** 2021-10-14 21:38 UTC
Labels: bug, UI, Needs Triage, BLOCKED
