### ISSUE TITLE
Runaway processes, namely udevd

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/embassy-os#901] opened 2021-12-04 15:17 UTC
![image](https://user-images.githubusercontent.com/39687477/144714812-389d688a-0aef-4a59-b594-74994ed04adf.png)

![image](https://user-images.githubusercontent.com/39687477/144714819-5cce8e7e-0e1b-4329-afeb-b2aea69d1066.png)

Reported by: @kn0wmad

**Comment by dr-bonez** [comment] 2021-12-04 17:57
Likely due to high container turnover. Will increase the cooldown on health checks, should help.

**Comment by ProofOfKeags** [comment] 2021-12-04 20:27
is there a ticket/PR you expect that change to land in or is this just something we want to keep open to track that?

**Comment by chrisguida** [comment] 2021-12-04 20:31
@dr-bonez would converting more actions to `inject` help with this?

**Comment by chrisguida** [comment] 2021-12-08 00:13
Created a ticket to track converting health checks to inject: https://github.com/Start9Labs/community-services/issues/1

**Comment by chrisguida** [comment] 2021-12-08 23:30
Escalating this to P1 since it makes a heavily used system progressively slower until everything is just hanging indefinitely.

**Comment by dr-bonez** [comment] 2021-12-09 22:25
so far cannot reproduce. @chrisguida please indicate the most concise steps to reproduce that you can.

**Comment by chrisguida** [comment] 2021-12-09 22:35
Basically you want to have as many `docker run` actions going at the same time as possible. I just converted all the health checks to inject, so you'll either need to use old builds, or you'll need to figure out how to run as many compat images as possible in parallel

**Comment by chrisguida** [comment] 2021-12-09 22:36
If we want to prohibit `docker run` health checks forever and phase out the system images, then that actually might be sufficient to solve this bug

**Comment by dr-bonez** [comment] 2021-12-09 23:19
if this is still an issue, we may just want to set [`udev.children_max`](https://www.freedesktop.org/software/systemd/man/systemd-udevd.html) in `cmdline.txt`

**Comment by chrisguida** [comment] 2021-12-12 22:16
Ok I have recreated this on hash b35f866c18dab292d86965f16e5200f431b83691 with all services up to date

<img width="1068" alt="Screen Shot 2021-12-12 at 4 11 50 PM" src="https://user-images.githubusercontent.com/7445670/145731673-106ee972-1467-4e90-b5ed-6afe8f71d857.png">

Steps to recreate: install bitcoind, run, wait about a minute for the healthchecks to run, see htop

**Comment by chrisguida** [comment] 2021-12-12 22:59
This bug also appears to be blocking system shutdowns.

**Comment by dr-bonez** [comment] 2021-12-14 21:33
Please report if this can ever be reproduced without using swap space

**Comment by pieslinger** [comment] 2021-12-15 05:10
I have hash 4317eeb5e6931539cf4efe0e925a708b64ae17fc and seem to have this issue on shutdown as well. The containers stop and I'll ssh into the embassy and run "shutdown" at the prompt. the machine will get to "Reached target power off" but then get stuck "waiting for process; system-udevd,.....on repeat. I have screen shots if required.

**Comment by chrisguida** [comment] 2021-12-15 13:51
@pieslinger screenshots are definitely welcome. Note that your commit is quite old and there have been several fixes to the health checks since that commit. When you get a chance I'd love to see if updating embassy-os makes the issue go away.

**Comment by ProofOfKeags** [comment] 2021-12-16 17:09
> This bug also appears to be blocking system shutdowns.

is udevd the cause for the shutdown issue? afaik, before Start9Labs/patch-db#17 is merged, there are issues with deadlocks that may prevent `embassyd` from shutting down correctly.

**Comment by chrisguida** [comment] 2021-12-16 18:17
I think there are multiple shutdown issues. The CPU-eating udevd processes block shutdown if they are present, but probably so do deadlocks in patch-db

**Comment by pieslinger** [comment] 2021-12-17 05:02
> @pieslinger screenshots are definitely always welcome. Note that your commit is quite old and there have been several fixes to the health checks since that commit. When you get a chance I'd love to see if updating embassy-os makes the issue go away.

Will grab a new commit and try again this weekend.

**Comment by dr-bonez** [comment] 2021-12-27 19:29
@chrisguida determine if #996 fixes this

**Comment by pieslinger** [comment] 2021-12-28 04:49
I have version ba5e450ad1ebaf3aca9b6be1e620f3720d8b6afe
The shutdown works much better than before but it still hangs on udevd for a couple minutes before completing the shutdown.

**Comment by dr-bonez** [comment] 2021-12-28 19:05
It is likely waiting on bitcoind to gracefully shutdown, which can take up to 5min

**Comment by pieslinger** [comment] 2021-12-28 19:22
I do not have any bitcoin software installed. Only running service is synapse.

**Comment by pieslinger** [comment] 2021-12-30 06:37
I have version ba5e450ad1ebaf3aca9b6be1e620f3720d8b6afe. Run docker stats -  only synapse container running. Run htop - see attached photo
![Screenshot from 2021-12-29 23-33-21](https://user-images.githubusercontent.com/87915068/147727726-02aa07b8-1f1b-4951-9cc9-2477bfc8dd85.png)
.

**Comment by chrisguida** [comment] 2021-12-30 18:03
@pieslinger do you have a [very] old version of synapse? this issue should have been fixed here https://github.com/Start9Labs/synapse-wrapper/commit/6c94cdbdcc0ccd70ce6ef0f0804ac97ef1974baf

**Comment by dr-bonez** [comment] 2021-12-30 19:41
@pieslinger please test with a commit after 268b9a349f80cf31f08cbafc9735875c104d5463

**Comment by pieslinger** [comment] 2021-12-30 19:44
If I build and flash this one: 4f6ff730ad9bc4b59b6f064ebea059a4afb5770a will that work?

**Comment by pieslinger** [comment] 2021-12-30 19:44
Is there a place to see the history of commits in one spot so I can check for myself? Very new to github

**Comment by ProofOfKeags** [comment] 2021-12-30 19:50
> Is there a place to see the history of commits in one spot so I can check for myself? Very new to github

https://github.com/Start9Labs/embassy-os/commits/integration/0.3.0

**Comment by pieslinger** [comment] 2021-12-30 20:02
thanks

**Comment by ProofOfKeags** [comment] 2021-12-30 20:09
> If I build and flash this one: 4f6ff73 will that work?

In case you hadn't figured this out yet. The answer to this is yes.

**Comment by chrisguida** [comment] 2021-12-30 23:00
@pieslinger the test will probably gather better data if you still have the old version of synapse with the `docker run` healthchecks. If you've already updated then no worries, I'll test later

**Comment by pieslinger** [comment] 2021-12-30 23:15
I have flashed 4f6ff730ad9bc4b59b6f064ebea059a4afb5770a and am just restoring synapse now. I'll report back if I continue to have udevd issues.

**Comment by chrisguida** [comment] 2022-01-11 00:09
Should we close this? @dr-bonez 

I feel like it might come back at some point, but it seems to be mitigated in 030

**Comment by chrisguida** [comment] 2022-01-14 16:27
This happened to me again today. System was under heavy load. Couldn't run `top` or `htop` for several minutes while running an install for Mastodon. Then I configured Mastodon and the system froze again for several minutes. When it came back there was a udevd process dominating the CPU:

<img width="1086" alt="Screen Shot 2022-01-14 at 10 23 17 AM" src="https://user-images.githubusercontent.com/7445670/149550129-b068ec4c-d5ac-443b-ace2-6267a2119e06.png">

**Comment by ProofOfKeags** [comment] 2022-01-14 18:27
We can't just eliminate the usage of all udevd processes. They do play a real role in the system, and it appears there is only one here. So I'm not sure how to handle this exactly. I'm not even sure from this reopen report that a problem exists.

**Comment by chrisguida** [comment] 2022-01-14 23:21
@ProofOfKeags see above discussion. These processes sit around eating 100% cpu forever. There's no way to make them go away unless you reboot. They accumulate slowly until your system just grinds to a halt. If we don't fix this, people will be required to reboot their systems every now and then.

**Comment by ProofOfKeags** [comment] 2022-01-15 01:38
You're saying that udevd *never* behaves properly?

**Comment by chrisguida** [comment] 2022-01-17 17:49
No, just that when it misbehaves, it *really* misbehaves.

**Comment by ProofOfKeags** [comment] 2022-01-17 17:57
Are you able to tell what the PPID is for the udevd process?

**Comment by chrisguida** [comment] 2022-01-17 18:08
I'm guessing theese processes are directly descended from process 1, since they are impossible to kill. But no, I cannot confirm this currently. Will need to wait for recreation.

**Comment by ProofOfKeags** [comment] 2022-01-17 18:12
Next time you run into it, run a `ps -aux` and grab the ppid's and find the process names associated with them. If they are direct descendents of initd, I have no earthly idea what to do about it since that suggests its an issue *beneath* embassy-os.

**Comment by chrisguida** [comment] 2022-01-17 18:15
Yes, based on my experience, it's definitely some kind of bad interaction between ubuntu and `docker run`.

**Comment by dr-bonez** [comment] 2022-01-17 21:25
a single udevd process at the top is not a problem. your system just *is* under heavy load. not much we can do about it without rewriting the scheduler.

**Comment by chrisguida** [comment] 2022-01-18 00:42
@dr-bonez no, these runaway processes keeps eating massive amounts of CPU even once the load has returned to normal.

@ProofOfKeags yep, parent process 1:
<img width="976" alt="Screen Shot 2022-01-17 at 6 41 01 PM" src="https://user-images.githubusercontent.com/7445670/149851674-d66767a6-70a6-4254-95f1-3de7180b783a.png">

**Comment by ProofOfKeags** [comment] 2022-01-18 01:11
Get the logs from systemd-udevd. Should be able to get at them from journald.

**Comment by chrisguida** [comment] 2022-01-18 01:31
@ProofOfKeags here's the relevant process, 4563. I wonder if this "probe" has anything to do with the issue:

```
-- Boot f2709d4aeea74f8e85bf09ca63a153c3 --
Jan 17 22:57:06 embassy systemd-udevd[2351]: Using default interface naming scheme 'v247'.
Jan 17 22:57:06 embassy systemd-udevd[2351]: ethtool: autonegotiation is unset or enabled, the speed and duplex are not writable.
Jan 17 22:57:06 embassy systemd-udevd[2351]: ethtool: autonegotiation is unset or enabled, the speed and duplex are not writable.
Jan 17 23:01:04 embassy systemd-udevd[4206]: Using default interface naming scheme 'v247'.
Jan 17 23:01:04 embassy systemd-udevd[4210]: regulatory.0: Process '/lib/crda/crda' failed with exit code 234.
Jan 17 23:01:04 embassy systemd-udevd[4220]: Using default interface naming scheme 'v247'.
Jan 17 23:01:06 embassy systemd-udevd[4217]: Using default interface naming scheme 'v247'.
Jan 17 23:01:06 embassy systemd-udevd[4216]: Using default interface naming scheme 'v247'.
Jan 17 23:02:06 embassy systemd-udevd[967]: loop243: Worker [4223] processing SEQNUM=6155 is taking a long time
Jan 17 23:02:06 embassy systemd-udevd[4223]: loop243: Spawned process 'probe-bcache -o udev /dev/loop243' [4563] is taking longer than 59s to complete
Jan 17 23:04:06 embassy systemd-udevd[967]: loop243: Worker [4223] processing SEQNUM=6155 killed
Jan 17 23:04:06 embassy systemd-udevd[967]: Worker [4223] terminated by signal 9 (KILL)
Jan 17 23:04:06 embassy systemd-udevd[967]: loop243: Worker [4223] failed
```

**Comment by chrisguida** [comment] 2022-01-18 01:35
Also seems like its parent process got killed

**Comment by chrisguida** [comment] 2022-01-18 15:32
Seems like it might be "bcache" that is causing these issues then: https://www.kernel.org/doc/html/latest/admin-guide/bcache.html

**Comment by dr-bonez** [comment] 2022-01-18 17:08
unfortunately the embassy isn't using bcache. at least mine is not. you can confirm this on your embassy by looking if /dev/bcache exists

**Comment by chrisguida** [comment] 2022-01-18 18:08
Why do you suppose `probe-bcache` would be running then?

**Comment by kn0wmad** [comment] 2022-01-18 21:42
My logs are similar:

![image](https://user-images.githubusercontent.com/39687477/150023296-272ebb1b-fc84-4396-84c9-2f2cbd2b62d6.png)

**Comment by ProofOfKeags** [comment] 2022-01-19 22:43
This seems to point to a network interface problem. But I'd need to look deeper to tell

**Comment by chrisguida** [comment] 2022-01-20 18:31
I believe `veth` interfaces are the ones generated by `docker run`, as this bug only seems to present when a `docker run` has occurred

**Comment by ProofOfKeags** [comment] 2022-01-31 16:44
This is a result of the kernel bug where processes do not respond to SIGKILL.

**Comment by ProofOfKeags** [comment] 2022-02-11 04:13
I'm closing this COB tomorrow if it hasn't reared its head by then.

**Comment by ProofOfKeags** [comment] 2022-02-11 17:58
> Has anyone been up for a week yet? I'm only on 5.5 days (no issues)

I've been up for a while. But that's besides the point. This ticket is clutter at this point. If no one is experiencing it after the raspios change then we should just close it. If it comes up later, we reopen.

**Comment by chrisguida** [comment] 2022-02-11 21:23
Haven't seen this since raspios. Will reopen if someone hits it.

**Closed by chrisguida** 2022-02-11 21:23 UTC
Labels: Bug, embassyd, P1 - Blocks Release, Performance
