### ISSUE TITLE
Mask the backup password

### ISSUE THREAD

**Issue by maupet** [Start9Labs/embassy-os#1417] opened 2022-04-25 22:18 UTC
Currently the backup password is visible to the user as it is input (both at backup and at restore).
The field should mask the password with asterisks.

**Comment by kn0wmad** [comment] 2022-04-26 02:04
Closing as duplicate of #1370

**Comment by elvece** [comment] 2022-06-23 19:54
Reopening to track resolving one of the two components needed to reimplement masking securely.

The second component is addressed [here](https://github.com/Start9Labs/embassy-os/issues/1370).

**Closed** 2022-06-27 19:51 UTC
Labels: Enhancement, UI, P1 - Blocks Release
