### ISSUE TITLE
[bug]: Occasionally all service frontends stop working, possibly due to migration

### ISSUE THREAD

**Issue by chrisguida** [Start9Labs/embassy-os#1061] opened 2022-01-13 17:19 UTC
Reboot is only remedy.

Steps to recreate:
1. Migrate from 02x
2. install TH chain
3. Launch TH
4. Go to TH .local URL
5. Observe that all service .onion and .local frontends are now broken

Current git hash: 3bf6e3fb2bf83874a584d1358907e5651decefa9

**Comment by ProofOfKeags** [comment] 2022-01-13 17:23
@chrisguida can you elaborate on what "occasionally" means?

**Comment by chrisguida** [comment] 2022-01-13 17:38
It means I haven't discovered a pattern. But it's happened the first time I started TH on two migrations in a row now, so perhaps that's a pattern.

**Comment by chrisguida** [comment] 2022-01-13 17:40
Shutdown hangs indefinitely actually, only hard reboot works. Possibly related to db locks

**Comment by dr-bonez** [comment] 2022-01-13 17:53
please define "broken"

**Comment by chrisguida** [comment] 2022-01-13 22:01
Unable to ping, unable to connect in a browser, unable to resolve

**Comment by ProofOfKeags** [comment] 2022-01-14 00:48
This seems like a duplicate of #1036

**Comment by ProofOfKeags** [comment] 2022-01-27 02:05
Closing as a ghost. Please reopen it if you encounter it.

**Closed by ProofOfKeags** 2022-01-27 02:05 UTC
Labels: Bug, embassyd, P1 - Blocks Release
