### ISSUE TITLE
Database connections running out, crashing Embassy

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/embassy-os#593] opened 2021-10-06 17:42 UTC
Error is: "pool timeout while waiting for an open connection".

Only remedy is reboot

Submitted by: @chrisguida

**Comment by ProofOfKeags** [comment] 2021-10-20 00:22
Closing this because I cannot reproduce this in any sensible way. If we encounter it again, we can reopen with new information. My best guess for the original cause of this is not that there was a resource leak but rather that the SSD became inaccessible due to hardware faults.

**Closed by ProofOfKeags** 2021-10-20 00:22 UTC
Labels: Bug, embassyd, Ghost, P1 - Blocks Release, Undiagnosed
