### ISSUE TITLE
[bug]: Instructions do not display for marketplace services over TOR ("Unknown Error")

### ISSUE THREAD

**Issue by bbqchef** [Start9Labs/embassy-os#959] opened 2021-12-16 04:10 UTC
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem, without success.

### EmbassyOS Version

0.3.0

### Device

Laptop/Desktop

### Device OS

Windows

### Device OS Version

Windows 10

### Browser

Tor Browser

### Browser Version

11.0.2

### Current Behavior

In marketplace, when clicking on a service's Instructions, "Unknown Error" is displayed. This happens when connecting to the Embassy using tor browser, both on a windows laptop and android phone. 

This does not happen when clicking on the same service from "Services" while using tor browser.

This also does not happen when connecting through LAN (firefox).

This seems to be the case for all services (tried 3, resulted in the same behavior).

The same behavior occurs with License.

![EOS3 Unknown Error](https://user-images.githubusercontent.com/96219817/146306036-cda69c82-bdc3-43d9-a836-56b5a11f8619.PNG)

![EOS Instructions](https://user-images.githubusercontent.com/96219817/146306419-2c9cbd63-bd60-4d44-b043-684eac30c80e.PNG)

### Expected Behavior

Instructions show properly.

### Steps to Reproduce

1. Connect to Embassy using Tor browser
2. Select market place
3. Select any service (say Bitcoin core)
4. Hit Instructions

**Comment by kn0wmad** [comment] 2021-12-16 04:35
I can reproduce on Tor Browser, standard security settings.  Looks like request is being blocked

![image](https://user-images.githubusercontent.com/39687477/146308804-d3f12dc6-cb30-4d77-9e95-618c783349bb.png)

**Comment by MattDHill** [comment] 2021-12-16 13:41
I assume this is the case for license as well?

**Comment by bbqchef** [comment] 2021-12-16 14:13
Correct, same thing happens with license.

**Comment by MattDHill** [comment] 2021-12-16 14:46
Looks like beta-registey blocking CORS requests. @dr-bonez since this request is being proxied by embassyd, can it be mapped such that Embassy is the origin? Probably preferable to enabling CORS for * on the registry.

**Comment by dr-bonez** [comment] 2021-12-16 15:42
The bug is that it's not being proxied by embassyd. If it was, cors wouldn't be an issue.

**Comment by MattDHill** [comment] 2021-12-16 16:29
Great, so we need to ensure that the URLs coming back from `marketplace/package/index` are not direct to the registry. Please assign this ticket accordingly.

**Comment by ProofOfKeags** [comment] 2021-12-16 17:33
Start9Labs/registry#82 may solve this implicitly but if not we will need to cut a ticket wrt making embassy-os responsible for doing URL translation.

**Comment by dr-bonez** [comment] 2021-12-16 21:56
looks like this isn't using the `static-files` section of patch-db, since its on the marketplace. So this needs to be a UI ticket, to prepend `/marketplace` to the relative urls returned by the registry. But it is blocked on https://github.com/Start9Labs/registry/issues/82

**Comment by dr-bonez** [comment] 2021-12-16 23:45
upon further investigation - it appears all traffic from the FE to the registry is going directly to the registry instead of using the embassy's reverse proxy.

**Comment by MattDHill** [comment] 2021-12-16 23:56
Correct, that was my original point. But this is not a FE issue. Take a look at Keagan's comment above for potential solution.

**Comment by dr-bonez** [comment] 2021-12-17 01:28
do we already have an issue for switching to the reverse proxy for marketplace access? We need to be using the reverse proxy.

**Comment by ProofOfKeags** [comment] 2021-12-17 20:31
how would it leak your tor address?

**Comment by dr-bonez** [comment] 2021-12-17 20:47
Origin header sent by the browser

**Comment by MattDHill** [comment] 2021-12-21 15:28
Not sure where this is at, assigning to @elvece and @DrewAns to get resolved.

**Comment by DrewAns** [comment] 2021-12-24 19:34
@MattDHill @elvece 
https://beta-registry-0-3.start9labs.com/package/instructions/embassy-pages
is the url coming from the BE.

**Comment by elvece** [comment] 2021-12-28 19:40
@DrewAns [This](https://github.com/Start9Labs/registry/issues/82) is deployed, instructions/icons/license will now look like this in the response from the registry:

`"instructions":"/package/instructions/embassy-pages","icon":"/package/icon/embassy-pages",`

My understanding is that the FE should now be sending that relative url to the BE, which will proxy to the registry. 

@dr-bonez were any changes needed in embassyd to account for this?

**Comment by DrewAns** [comment] 2021-12-28 19:42
@lucy that's correct.  I'm on my way to the office, will flash/test when I arrive

**Comment by dr-bonez** [comment] 2021-12-28 19:46
The frontend still needs to prepend `/marketplace` to each of those urls.

**Comment by BitcoinMechanic** [comment] 2021-12-29 04:17
This may be related: Service icons aren't rendering. Using Firefox in private browsing.
![Screen Shot 2021-12-28 at 8 10 59 PM](https://user-images.githubusercontent.com/45926711/147626974-88201c49-cf40-4476-8a97-f99098069cbd.png)

**Closed** 2022-01-04 18:31 UTC
Labels: Bug, UI, P1 - Blocks Release
