### ISSUE TITLE
embassy.local/#/init LAN instructions html link is 404

### ISSUE THREAD

**Issue by dme1sc** [Start9Labs/embassy-os#879] opened 2021-12-01 02:53 UTC
Broken html link for step-by-step lan instructions in embassy.local/#/init page.

On initial success of loading Embassy 0.3.0, the http://embassy.local/#/init page is presented.  Scroll down to the LAN instructions section and before the LAN address is a line that reads:
For step-by-step instructions, click here.
Click the link and get a 404 error.
It resolves to:  https://docs.start9.com/user-manual/general/lan-setup.html
I confirmed this page does not exist.  It appears to need to point to:
https://docs.start9.com/user-manual/connecting.html#lan

This is not the same issue as #753: https://github.com/Start9Labs/embassy-os/issues/753
That deals with the same page but does not reference the incorrect link in the step-by-step instructions line.  
See image attached.

![init page bad link to user-manual](https://user-images.githubusercontent.com/89276154/144162808-a211aa2d-3c1f-4341-bc45-66145addd1ce.PNG)

**Comment by kn0wmad** [comment] 2021-12-01 03:11
Thanks for the report, but this is a duplicate of #363 - Documentation is still under construction, so links may not point to the right places yet as we get that wrapped up.  Closing for now

**Closed by kn0wmad** 2021-12-01 03:11 UTC
Labels: Bug, Needs Triage
