### ISSUE TITLE
[bug]: Service Installation failure results in package stuck mid-install

### ISSUE THREAD

**Issue by elvece** [Start9Labs/embassy-os#905] opened 2021-12-05 16:00 UTC
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem, without success.

### EmbassyOS Version

0.3.0

### Device

Laptop/Desktop

### Device OS

MacOS

### Device OS Version

10.15.7

### Browser

Firefox

### Browser Version

94.0.2

### Current Behavior

Installing a bunch of services (~10) at once causes the service to be stuck at the downloading step (52%) and throws the following error:

```
Failed: Filesystem I/O Error: request or response body error: error reading a body from connection: end of file before message length reached 
```

Running `systemctl restart embassy` clears the installing services from the UI, but this error appears in logs:

```
Dec 05 05:54:05 embassy-7fed63b1 embassyd[6257]: Dec 05 05:54:05.549  WARN shutdown: embassy::context::rpc: 1 RPC Context(s) are still being held somewhere. This is likely a mistake.
Dec 05 05:54:05 embassy-7fed63b1 embassyd[6257]: The application panicked (crashed).
Dec 05 05:54:05 embassy-7fed63b1 embassyd[6257]: Message:  RpcContext used after shutdown!
Dec 05 05:54:05 embassy-7fed63b1 embassyd[6257]: Location: src/context/rpc.rs:339
Dec 05 05:54:05 embassy-7fed63b1 embassyd[6257]: Backtrace omitted.
```

Running `embassy-cli db dump` reveals the service stuck at installing does not exist. 

There are no IO errors in dmesg logs.

### Expected Behavior

All services should install without error when installing many in parallel.

### Steps to Reproduce

1. Start installing all services from the marketplace.
2. Notice that one of them will fail as you install many at once. 
3. The failed install will be stuck at 53% until embassyd is restarted.

**Comment by ProofOfKeags** [comment] 2021-12-05 18:49
It's possible this may be a limitation of the registry itself as well. It appears that the issue is related to receiving an EOF before the response body is supposed to terminate, suggesting that it may have overloaded the concurrent connections the registry can support. Next time you run into this it is worth looking through the registry logs at the same time to see if there is any issue there.

**Comment by dr-bonez** [comment] 2021-12-17 01:50
please retry now that https://github.com/Start9Labs/patch-db/issues/16 has been merged

**Comment by elvece** [comment] 2021-12-21 18:36
This is still happening on ab4d1e2c3f7d6b809d3c50ba24d3297f39661475

**Comment by kn0wmad** [comment] 2021-12-21 19:30
I also just reproduced this on eca381ff

**Comment by dr-bonez** [comment] 2021-12-22 03:31
the error shown indicates a network disconnect. Is it possible this is a registry issue?

**Comment by ProofOfKeags** [comment] 2021-12-30 17:19
assigning to @dr-bonez for triaging

**Comment by elvece** [comment] 2022-01-13 15:44
Happened with mastodon as well yesterday. 
<img width="1674" alt="Screen Shot 2022-01-13 at 1 02 40 AM" src="https://user-images.githubusercontent.com/12953208/149298792-4f82bab6-cd11-4876-8d2d-9fbae4ce0ff4.png">

The registry did not indicate any errors in the logs.

**Comment by dr-bonez** [comment] 2022-01-13 18:04
I mean the error definitely indicates this is the tcp connection being closed before all bytes could be downloaded. Is this still presenting as a "stuck" download? Or is the app going away?

**Comment by ProofOfKeags** [comment] 2022-01-13 20:07
We cannot, in general, guarantee that the TCP connection won't get interrupted, so the important part here is that if a package fails due to a reset connection, it should leave the system in a workable state.

**Comment by elvece** [comment] 2022-01-15 00:19
> I mean the error definitely indicates this is the tcp connection being closed before all bytes could be downloaded. Is this still presenting as a "stuck" download? Or is the app going away?

It's presenting as a stuck download.

**Comment by elvece** [comment] 2022-01-18 20:42
Additional details with unstable flag turned on (cleanup failed on sideloading s9pk):
<img width="1281" alt="Screen Shot 2022-01-18 at 1 37 51 PM" src="https://user-images.githubusercontent.com/12953208/150015271-5185bafb-1c61-4d33-bfde-09938eb5435c.png">

**Closed** 2022-01-24 16:51 UTC
Labels: Bug, embassyd, P1 - Blocks Release, Needs Diagnosis
