### ISSUE TITLE
[bug]: Service does not enter "Restarting" state when config is changed on a "Running" service

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/embassy-os#1743] opened 2022-08-17 21:02 UTC
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem.

### EmbassyOS Version

0.3.1.1

### Device

Laptop/Desktop

### Device OS

Linux

### Device OS Version

5.18

### Browser

Firefox

### Browser Version

102

### Current Behavior

It is not obvious that a service is restarting when you reconfigure it (while in a Running state)

### Expected Behavior

Enter Restarting state

### Steps to Reproduce

1. Start Bitcoin service (for example)
2. Change config while running
3. Service will restart, but this is not indicated in the UI

**Comment by chrisguida** [comment] 2022-08-17 21:16
100% we need this fixed

**Comment by elvece** [comment] 2022-12-14 23:18
Dupe of #958

**Closed by elvece** 2022-12-14 23:18 UTC
Labels: Enhancement, embassyd
