### ISSUE TITLE
[bug]: Shutdown does not work smoothly

### ISSUE THREAD

**Issue by chrisguida** [Start9Labs/embassy-os#956] opened 2021-12-15 03:15 UTC
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem, without success.

### EmbassyOS Version

b6429beb945d21b519bc207701b5841ce0b37582

### Device

Laptop/Desktop

### Device OS

Other

### Device OS Version

backend

### Browser

Other

### Browser Version

backend

### Current Behavior

I've rarely had shutdown complete faster than a few minutes, and I've never actually heard the shutdown noise play. The only time it shuts down in under 5m is when there are no services running and few services installed. About half the time it hangs indefinitely.

### Expected Behavior

When the user hits shutdown, the embassy should play the shutdown noise and shut down, or it should tell the user what it's doing to prepare for shutdown. The user should not be sitting waiting for several minutes wondering what's happening.

### Steps to Reproduce

1. Install some services
2. Optionally run some of them
3. Hit Embassy->Shutdown
4. Wait several minutes
5. No sound plays

### Anything else?

Related to this: https://github.com/Start9Labs/embassy-os/issues/953

And probably related to deadlocks in patch-db?

**Comment by k0gen** [comment] 2021-12-15 15:54
I can confirm the same behavior on b4cf717e572c9e4e4ebee4586d692e442a61a7a0

**Comment by ProofOfKeags** [comment] 2021-12-16 17:04
I believe this is fixed by Start9Labs/patch-db#17

**Comment by dr-bonez** [comment] 2021-12-16 21:23
cannot reproduce on 6cd01d9b849fa6ef890f5b458321edb7712830d6

**Comment by chrisguida** [comment] 2021-12-16 22:23
will update and test

**Comment by chrisguida** [comment] 2021-12-30 20:30
I've been having smooth shutdowns recently. Will reopen if it happens again.

**Comment by chrisguida** [comment] 2022-01-14 01:20
Seeing this issue again. I hit shutdown, and these containers appear to be stopped, but then they pop back up and stay up. I'm guessing this is a db issue because somehow the containers are not being put into stopped status, so embassyd is restarting the containers even though they've already been stopped.

```
~# docker ps
CONTAINER ID   IMAGE                                     COMMAND                  CREATED          STATUS          PORTS     NAMES
34c9a1dd54d7   start9/ride-the-lightning/main:0.11.0.1   "docker_entrypoint.sh"   32 seconds ago   Up 29 seconds   80/tcp    ride-the-lightning.embassy
f61c03a84d5a   start9/filebrowser/main:2.14.1.1          "docker_entrypoint.sh"   33 seconds ago   Up 29 seconds             filebrowser.embassy

```

Steps to reproduce:

1. install and run these services:
<img width="1436" alt="14-services" src="https://user-images.githubusercontent.com/7445670/149434739-1ffcaeb1-b06c-4731-8e43-3c91856e2904.png">
2. Hit shutdown
3. `docker ps`

**Closed** 2022-01-20 19:35 UTC
Labels: Bug, embassyd, P1 - Blocks Release
