### ISSUE TITLE
[feat]: allow raw ip addresses in the `hostname` field during cifs backups

### ISSUE THREAD

**Issue by k0gen** [Start9Labs/embassy-os#927] opened 2021-12-09 15:59 UTC
##
![Screenshot from 2021-12-09 16-37-23](https://user-images.githubusercontent.com/3606313/145431289-954b6f25-7a7b-411f-8901-5f949ded0582.png)
![Screenshot from 2021-12-09 17-02-51](https://user-images.githubusercontent.com/3606313/145431740-a6f89c6c-6072-4dc7-a193-16b5b5c5608d.png)

# Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem, without success.

### EmbassyOS Version

0.3.0 commit hash c2bb1e69be9878d93c471fafab780e603c244cfc

### Device

Laptop/Desktop

### Device OS

Linux

### Device OS Version

elementary OS 6

### Browser

Firefox

### Browser Version

94

### Current Behavior

When adding New Shared Folder hostname.local or IP address won't work.

### Expected Behavior

support hostnames and IP addresses 

### Steps to Reproduce

Just add your New Shared Folder

**Comment by dr-bonez** [comment] 2021-12-10 01:09
Currently, the os uses `nmblookup` to determine the ip address of the shared folder's host upon mount. This is more reliable than a raw ip address, since raw ip addresses change over time, when dhcp leases expire. We can allow for a raw ip as a hostname, however this leaves an open question: if a user sends a raw ip address, should we save it, and expect the user to edit it every time it changes? Or should we not save it, and expect them to enter it again the next time around, under the expectation that the ip address would likely change between backups.

@MattDHill please advise.

**Comment by MattDHill** [comment] 2021-12-10 03:56
Game plan is to add mDNS support for hostname field. So either the raw hostname (e.g. My Laptop) or the mDNS hostname (e.g. my-laptop.local) will work, but not raw IP. As Aiden mentioned, IPs are ephemeral, and these entries are meant to persist. Furthermore, it is simple enough to obtain either of the supported options on all platforms (Mac, Windows, Linux); there is no need to support IP also.

**Comment by k0gen** [comment] 2021-12-10 12:59
Call me an old timer but whenever I can't connect via hostname I tend to try using the IP address for the box I'm trying to connect too.

Ditching IP support is a bold move @MattDHill .
This kind of resembles Apple letting go of the floppy drive, leaving only a re-writable CD drive and 10 years later killing CD drive, as well. I'm not sure about it but I do love bold moves!
So you guys decide if IP is here to stay or not.

**Comment by MattDHill** [comment] 2021-12-10 14:05
You're not an old timer, you just know what an IP is haha. Most future users will not. Also, while I appreciate the comparison, Start9 rejecting IP for a single input field is a far cry from essentially deprecating billions of dollars of hardware media, especially since supporting IP for this field could lead to confusion and frustration for many users.

Look, we could very easily support IP for cifs. The problem is that we save the cifs record, but the IP is going to change. So at minimum we need to message it differently to the user (e.g. "Because you entered an IP, this may not work next time") and at most we need to build a different UX around it (e.g. we don't persist the IP, but rather, require that be typed in fresh every time).

I suppose the former would be sufficient, so long as we don't advertise that IP is the recommended way. Then only advanced users who know what it is will use it. I still don't understand though why you would prefer to use IP over hostname or mDNS hostname.

**Comment by k0gen** [comment] 2021-12-11 13:43
@dr-bonez just tried 6942eda4323224055af3fae207c00ccc2c450ce3 and still no go.
I'm getting Connection Failed
![Embassy Setup 4](https://user-images.githubusercontent.com/3606313/145678827-eb635a54-02e8-49c2-881d-3290a48e7e69.png)
Screenshot taken on latest iPadOS

**Comment by dr-bonez** [comment] 2021-12-15 00:38
fixed by #933

**Closed by dr-bonez** 2021-12-15 00:38 UTC
Labels: Enhancement, embassyd, P1 - Blocks Release
