### ISSUE TITLE
UI may have a memory leak

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/embassy-os#779] opened 2021-11-09 16:59 UTC
Embassy Metrics page becomes unreachable (tab seems to crash) and gives 'out of memory' error.

![image](https://user-images.githubusercontent.com/39687477/140969886-27e11d24-e236-4672-83d1-c4f1b1c5db99.png)

Reported by: @kn0wmad

**Comment by MattDHill** [comment] 2021-11-09 22:30
I cannot reproduce. @kn0wmad please try to reproduce this while taking occasional memory snapshots from the browser.

**Comment by kn0wmad** [comment] 2021-11-10 01:44
With the exception of the error messages, the results are similar to this issue, happening on same page:

![image](https://user-images.githubusercontent.com/39687477/141034344-81788206-2b85-4283-ad4e-074461cb0042.png)

**Comment by ProofOfKeags** [comment] 2021-11-11 23:18
@MattDHill are you attempting to reproduce with Mocks only? I anticipate this is not something that can be detected by largely static data.

**Comment by MattDHill** [comment] 2021-11-11 23:23
> @MattDHill are you attempting to reproduce with Mocks only? I anticipate this is not something that can be detected by largely static data.

Correct, no love testing to date. @kn0wmad taking snapshots of the browser memory tab over time should reveal a leak.

**Comment by kn0wmad** [comment] 2021-11-12 19:54
Will do

**Comment by ProofOfKeags** [comment] 2021-11-15 18:02
@kn0wmad have you had a chance to collect that data?

**Comment by kn0wmad** [comment] 2021-11-16 01:42
I took several snapshots and did not see any drastic data.  I'm wondering if this is related to the healthcheck process that was destroying my system.  Could that produce this result?

**Comment by MattDHill** [comment] 2021-11-16 01:55
Yes, that's most likely it IMO. We should close this ticket and address if/when if happens again.

**Comment by kn0wmad** [comment] 2021-11-16 01:58
Closing for now.  Will keep an eye on possible causes.

**Comment by ProofOfKeags** [comment] 2021-11-16 17:22
@kn0wmad a healthcheck process that hurts your system wouldn't change anything about the memory footprint of the UI which runs on an entirely separate machine. It is almost certainly the case that it would have zero impact here. If we can't reproduce we can leave this closed but keep in mind that the idea presented as a potential cause is not consistent with how things work.

**Comment by MattDHill** [comment] 2021-11-16 17:33
I don't think we can conclude that the "out of memory" error originated with the FE. It seems possible the FE was displaying this error because it was thrown by the BE.

**Comment by ProofOfKeags** [comment] 2021-11-16 17:35
We absolutely can. That error is browser originated.

**Comment by MattDHill** [comment] 2021-11-16 17:45
Then this issue should not be closed

**Comment by DrewAns** [comment] 2021-11-16 22:37
Monitored the page.  Memory use fluctuated from 45 to 128 MBs.  Always went back down.  No evidence of leak.

**Closed** 2021-11-16 22:36 UTC
Labels: Bug, UI, Needs Triage
