### ISSUE TITLE
[bug]: "Cannot connect" toasts don't go away even after connection is reestablished

### ISSUE THREAD

**Issue by chrisguida** [Start9Labs/embassy-os#1330] opened 2022-03-13 21:00 UTC
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem, without success.

### EmbassyOS Version

0.3.0

### Device

Laptop/Desktop

### Device OS

Happens on all my devices

### Device OS Version

it doesn't matter

### Browser

Other

### Browser Version

also doesn't matter

### Current Behavior

"Unable to connect" toasts stack up on top of each other, covering the bottom of the UI, if my network connection goes down, or if the embassy goes down. Then once the connection is reestablished, they're still there. The easiest way to make them go away is to refresh the page. The tedious way is to click on each toast in turn (there are often several).

### Expected Behavior

The toast should disappear once the connection is reestablished. Alternatively, a simple press of the ESC key should make them all disappear.

### Steps to Reproduce

1. Log into UI
2. Disconnect internet
3. Wait for toast to appear
4. Reconnect internet
5. Toast is still there

### Anything else?

<img width="830" alt="Screen Shot 2022-03-13 at 3 51 54 PM" src="https://user-images.githubusercontent.com/7445670/158078994-2f38cad1-b0e6-4186-8349-2399bd02d834.png">
<img width="753" alt="Screen Shot 2022-03-13 at 3 54 49 PM" src="https://user-images.githubusercontent.com/7445670/158078992-16f4d458-516a-4c84-8e69-1af5941c2783.png">

**Comment by kn0wmad** [comment] 2022-03-14 00:41
CC @DrewAns

**Comment by ProofOfKeags** [comment] 2022-03-15 17:58
Yeah this is super annoying.

**Comment by DrewAns** [comment] 2022-03-15 22:20
@ProofOfKeags am i assigned to this ticket?

**Comment by kn0wmad** [comment] 2022-03-16 14:08
> @ProofOfKeags am i assigned to this ticket?

Assigning to you as this is UI

**Comment by MattDHill** [comment] 2022-03-21 22:11
I am unable to reproduce. Can you tell if these toasts are popping up at the same time? Or are they stacking gradually over time?

**Comment by chrisguida** [comment] 2022-03-21 23:21
I think stacking up gradually, though I would need to watch more closely. When you say you can't reproduce, do you mean you're not seeing the toasts at all?

**Comment by MattDHill** [comment] 2022-03-22 02:17
No, if I lose network connectivity, the toast displays. If connectivity comes back, it dismisses. I am unable to reproduce your issue. Basic test I'm running is to turn off WiFi then turn it back on. Others have run into this, but reliable reproduction would help resolve it.

**Comment by MattDHill** [comment] 2022-03-22 19:04
So maybe triggered by a websocket error specifically? How many stack up? Is it always the same?

**Comment by chrisguida** [comment] 2022-03-22 19:09
Seems different every time. I've seen 1 sometimes, other times a few (~3-5) stacked. Usually no more than that. I think. Either that or I just get impatient and refresh the page, which makes the toasts go away.

**Comment by chrisguida** [comment] 2022-03-23 18:23
Yes, that is the scenario that usually precipitates this issue. Leave tabs overnight, come back and there's a bunch of toasts

**Comment by elvece** [comment] 2022-04-11 17:05
@dr-bonez This is still an issue but is being addressed in Alex's refactor of the component this bug lives in. 

Phase one of refactor: https://github.com/Start9Labs/embassy-os/pull/1359

**Comment by elvece** [comment] 2022-05-04 18:47
I have not been able to repro during testing of this [PR](https://github.com/Start9Labs/embassy-os/pull/1412). The refactor of `app.component` to simplify ordering of initialization actions seems to have resolved this bug.

**Closed** 2022-06-07 00:07 UTC
Labels: Bug, UI, P2 - Desirable
